package org.shahid.annotations.entity;

import java.lang.annotation.*;

/**
 * The GenerateDataAcess annotation type, used to flag bean/DTO interfaces which
 * corresponding data access implementation will be generated by
 * GenerateDataAccessProcessor.
 *
 * @author Shaikh Shahid Iqbal
 */
@Documented
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.SOURCE)
public @interface GenerateDataAccess {

    /**
     * A custom JPQL expression used when generating custom find/search methods.
     */
    String value() default "";
}
